add multiple method calls for unit test grader
codio/parsons-puzzle-ui pull request #19
Opened 2020-03-24 08:14 UTC by mint87

2020-03-24 08:16 UTC, mint87 commented
https://codio.myjetbrains.com/youtrack/issue/codio-11232

2020-03-24 12:00 UTC, mloginov commented
need to support structures like this

```
def testOne(self):\n' +
                  '    self.assertEqual(maxindex([0, 2, 4]),2,' +
                          '"Calling function <code>maxindex([0, 2, 4])</code>.")\n' +
                  '    self.assertEqual(maxindex([7, 2, 4]),0,' +
                          '"Calling function <code>maxindex([7, 2, 4])</code>.")\n' +
                  '    self.assertEqual(maxindex([7, 8, 4]),1,' +
                          '"Calling function <code>maxindex([7, 8, 4])</code>.")\n' +
```

so interfaces should be like this

```
export interface AssertEqualParams {
  methodCall: string;
  expectedOutput: string;
  errorMessage?: string;
}

export interface UnitTest {
  testName: string, // maybe store test name (testOne for example)
  assertEquals: AssertEqualParams[]
}

```

2020-03-25 06:39 UTC, destitutus commented
conflicts here

2020-04-08 06:44 UTC, mloginov requested changes

2020-04-08 06:44 UTC, mloginov commented on src/lib/render.ts
> +export const renderUnitTest = (test?: AssertEqualParams): Cash => {
`UnitTest` should be passed as param to `renderUnitTest`

2020-04-08 06:44 UTC, mloginov commented on src/lib/render.ts
> +    tests.forEach((test: UnitTest) => testsList.append(renderUnitTest(test.assertEquals)))
`test` should be passed as param to `renderUnitTest`

2020-04-08 06:44 UTC, mloginov commented on src/lib/data-helper.ts
> +export const collectUnitTest = (container: Cash): AssertEqualParams => {
`collectUnitTest` should collect `UnitTest` not `AssertEqualParams`
with `UnitTest.name`

2020-04-08 06:44 UTC, mloginov commented on src/lib/data-helper.ts
> +  const unitTests: AssertEqualParams[] = []
should be `const unitTests: UnitTest[] = []`

2020-04-08 06:44 UTC, mloginov commented on src/lib/data-helper.ts
> +    ...unitTests.map((test: AssertEqualParams, index: number): string => [
should be `test: UnitTest`

2020-04-08 06:44 UTC, mloginov commented on src/lib/data-helper.ts
>        `  def test_${index}(self):`,
need to restore name from `unitTest.name`

2020-04-08 12:43 UTC, mloginov requested changes

2020-04-08 12:43 UTC, mloginov commented on src/lib/data-helper.ts
> +      `  def ${test.name}(self):`,
if `test.name` is empty need to use `test_${index}`

2020-04-08 12:43 UTC, mloginov commented on src/lib/render.ts
> +  $(testContainer).data('data-name', test ? test.name : '')
maybe change to `test-name`?

2020-04-08 13:52 UTC, mloginov approved these changes

2020-04-10 06:07 UTC, merged